name: AutoCommit
on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:

  build:
    name: Create Commit
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Create local changes
        run: |
          echo -e "\t \n" >> README.md
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automatic changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Scope for Go
        uses: undefinedlabs/scope-for-go-action@1.1.0
        with:
          dsn: ${{ secrets.SCOPE_DSN }}
